export default {
  'Place with given name does not exist': 'Miejsce o podanej nazwie nie istnieje.',
  'Opinion not found': 'Opinia nie została odnaleziona.',
  'You have no permission to delete this resource': 'Nie posiadasz uprawnień by usunąć ten zasób.',
  'You have already liked this opinion': 'Ta opinia została już przez Ciebie polubiona.',
  'You did not like this opinion': 'Ta opinia nie została przez Ciebie polubiona.',
  'You provide invalid report reason': 'Podano niepoprawny powód zgłoszenia opinii.',
  'User not found': 'Użytkownik nie został odnaleziony',
  'You have already reported this opinion.': 'Ta opinia została już przez Ciebie zgłoszona.',
  'Report creation failed': 'Wystąpił błąd podczas rejestracji zgłoszenia opinii.',
  'Place with that name already exists': 'Miejsce o danej nazwie już istnieje.',
  'Places not found': 'Miejsce nie zostało odnalezione.',
  'Tag with that name already exists': 'Tag o podanej nazwie już istnieje',
  'Tags not found': 'Tag nie został odnaleziony',
  'User with that email already exists': 'Użytkownik o podanym adresie email już istnieje.',
  'User with that username already exists': 'Użytkownik o podanej nazwie już istnieje.',
  'You are banned': 'Twoje konto zostało zablokowane. Skontaktuj się z administracją.',
  'User not exists': 'Taki użytkownik nie istnieje.',
  'Wrong password': 'Podano niepoprawne hasło.',
  'Invalid request data.': 'Przesłane dane są niepoprawne.'
};
